GEMINI_API_KEY="AIzaSyCJeRsnbZkK4VdNw93JwfQDgu65om9xXXc"
GOOGLE_API_KEY="AIzaSyCJeRsnbZkK4VdNw93JwfQDgu65om9xXXc"
PINECONE_API_KEY="pcsk_qDF5H_5zMh1Bmg2zp5XAYn3usYPhPDn4axHdG2bip66dpaQxZxfgSd99u5sQxh9DhYrVX"
PINECONE_ENV= "gcp-starter"